# Generated by Django 5.2.4 on 2025-07-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("publication_year", models.IntegerField()),
            ],
            options={
                "permissions": [
                    ("can_view", "Can view documents"),
                    ("can_create", "Can create documents"),
                    ("can_edit", "Can edit documents"),
                    ("can_delete", "Can delete documents"),
                ],
            },
        ),
    ]
