# Generated by Django 5.2.4 on 2025-08-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="published_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
