# Generated by Django 5.2.4 on 2025-07-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("relationship_app", "0003_alter_book_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(default=2000),
        ),
    ]
